export default [
  "strapi::logger",
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "market-assets.strapi.io",
            "res.cloudinary.com",
            "localhost:*",
            "127.0.0.1:*",
            "*.localhost:*",
            "http://localhost:*",
            "http://127.0.0.1:*",
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            "market-assets.strapi.io",
            "res.cloudinary.com",
            "localhost:*",
            "127.0.0.1:*",
            "*.localhost:*",
            "http://localhost:*",
            "http://127.0.0.1:*",
          ],
          "script-src": [
            "'self'",
            "'unsafe-inline'",
            "'unsafe-eval'",
            "localhost:*",
            "127.0.0.1:*",
          ],
          "style-src": [
            "'self'",
            "'unsafe-inline'",
            "localhost:*",
            "127.0.0.1:*",
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  {
    name: "strapi::cors",
    config: {
      headers: "*",
      origin: [
        "http://localhost:3000",
        "http://localhost:4000",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:4000",
        "http://127.0.0.1:8443",
      ],
    },
  },
  "strapi::poweredBy",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  {
    name: "strapi::public",
    config: {
      path: "./public",
      maxAge: 31536000,
      defer: false,
    },
  },
  "global::deepPopulate",
];
