services:
  app-blue:
    container_name: armanstudio-blog-blue
    image: armanstudio-blog-i:blue
    build:
      context: .
    ports:
      - "4001:4000"
    env_file:
      - .env.local
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:4000"]
      interval: 10s
      timeout: 5s
      retries: 3

  app-green:
    container_name: armanstudio-blog-green
    image: armanstudio-blog-i:green
    build:
      context: .
    ports:
      - "4002:4000"
    env_file:
      - .env.local
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:4000"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: armanstudio-proxy
    ports:
      - "4000:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./upstream.conf:/etc/nginx/upstream.conf
    depends_on:
      - app-blue
      - app-green