services:
  strapi:
    image: strapi-erfanweb:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
    volumes:
      - strapi-data:/opt/app/.tmp
      - strapi-uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"

volumes:
  strapi-data:
  strapi-uploads: