version: '3'

services:
  strapi:
    container_name: strapi
    build:
      dockerfile: Dockerfile.prod
    image: strapi-prod:latest
    restart: unless-stopped

    env_file:
      - .env.production

    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      NODE_ENV: production

    volumes:
      - ./public:/opt/app/public
      - ./.tmp:/opt/app/.tmp

    ports:
      - "8080:1337"

    networks:
      - strapi



networks:
  strapi:
    name: Strapi
    driver: bridge