services:
  strapi:
    image: docker.io/${DOCKER_USERNAME:-erfanweb}/strapi-erfanweb:latest
    build: null
    environment:
      NODE_ENV: production
      PUBLIC_URL: ${PUBLIC_URL:-http://localhost:1337}
      STRAPI_ADMIN_CLIENT_URL: ${STRAPI_ADMIN_CLIENT_URL}
      STRAPI_ADMIN_CLIENT_PREVIEW_SECRET: ${STRAPI_ADMIN_CLIENT_PREVIEW_SECRET}
    volumes:
      - ./public/uploads:/opt/app/public/uploads
      - ./.env:/opt/app/.env
      - ./.tmp:/opt/app/.tmp
    command: npm run start
