import {
  IconBolt,
  IconBrain,
  IconBrandDocker,
  IconBrandOpenai,
  IconBrandPython,
  IconBrandZapier,
  IconBriefcase,
  IconChartBar,
  IconChartHistogram,
  IconClock,
  IconCloud,
  IconCode,
  IconDatabaseSearch,
  IconEye,
  IconMessageChatbot,
  IconMoodSmile,
  IconPencil,
  IconPencilBolt,
  IconPlug,
  IconPlugConnected,
  IconRobot,
  IconRocket,
  IconSearch,
  IconSparkles,
  IconTrendingDown,
} from '@tabler/icons-react';
import { Icon } from '@tabler/icons-react';

const iconMap: Record<string, Icon> = {
  IconMessageChatbot,
  IconRobot,
  IconEye,
  IconChartHistogram,
  IconDatabaseSearch,
  IconPlugConnected,
  IconSearch,
  IconPencil,
  IconPencilBolt,
  IconCode,
  IconRocket,
  IconSparkles,
  IconPlug,
  IconBriefcase,
  IconChartBar,
  IconBolt,
  IconBrain,
  IconClock,
  IconCloud,
  IconMoodSmile,
  IconTrendingDown,
  IconBrandDocker,
  IconBrandOpenai,
  IconBrandPython,
  IconBrandZapier,
};

export function getTablerIcon(name?: string): Icon {
  if (!name) return IconSparkles;
  return iconMap[name] ?? IconSparkles;
}
